import { Component, inject, signal } from '@angular/core';
import { BaseTableComponent, TableAction } from '../../base/base-table/base-table.component';
import { BaseDialogComponent } from '../../base/base-dialog/base-dialog.component';
import { BaseDatePickerComponent } from '../../base/base-date-picker/base-date-picker.component';
import { BaseToastService } from '../../base/base-toast/base-toast.service';
import { leads, LeadStatus } from '../../shared/mock-data';
@Component({selector:'app-consultant-leads-page',standalone:true,imports:[BaseTableComponent,BaseDialogComponent,BaseDatePickerComponent],template:`<section class="screen-stack consultant-dashboard"><article class="hero-card"><small>داشبورد مشاور</small><h2>لیدهای من</h2><p>تماس با کاربران، ثبت یادداشت، ساخت پرونده و رزرو نوبت.</p></article><app-base-table [columns]="columns" [rows]="leads" [filters]="filters" [customActions]="actions" [showEdit]="false" [showDelete]="false" (add)="open('افزودن لید')" /></section><app-base-dialog [open]="!!dialog()" [title]="dialog()" [confirmLabel]="confirmLabel()" (closed)="dialog.set('')" (confirm)="save()"><div class="form-grid">
@if (dialog() === 'ثبت یادداشت') {<textarea class="control" placeholder="متن یادداشت داخلی"></textarea><select class="control"><option>عمومی</option><option>مهم</option><option>نیازمند پیگیری</option></select>}
@else if (dialog() === 'ساخت پرونده') {<input class="control" placeholder="نام بیمار"/><input class="control" placeholder="کد ملی"/><input class="control" placeholder="درمان اولیه"/><textarea class="control" placeholder="شرح پرونده"></textarea>}
@else if (dialog() === 'رزرو نوبت') {<input class="control" placeholder="نام بیمار"/><app-base-date-picker label="تاریخ نوبت"/><select class="control"><option>10:00</option><option>12:30</option><option>16:30</option></select><textarea class="control" placeholder="توضیح رزرو"></textarea>}
@else {<input class="control" placeholder="نام لید"/><input class="control" placeholder="موبایل"/><input class="control" placeholder="درمان موردنظر"/><textarea class="control" placeholder="جزئیات اولیه"></textarea>}
</div></app-base-dialog>`})
export class ConsultantLeadsPage{private toast=inject(BaseToastService);leads=leads;dialog=signal('');columns=[{key:'name',label:'نام'},{key:'phone',label:'تلفن'},{key:'status',label:'وضعیت'},{key:'description',label:'توضیحات'}];filters=[{key:'status',label:'وضعیت',type:'select' as const,options:[LeadStatus.New,LeadStatus.Called]},{key:'description',label:'درمان',type:'text' as const}];actions:TableAction[]=[{icon:'fa-solid fa-phone',label:'تماس با کاربر',onClick:()=>this.callUser()},{icon:'fa-solid fa-note-sticky',label:'ثبت یادداشت',onClick:()=>this.open('ثبت یادداشت')},{icon:'fa-solid fa-hospital-user',label:'ساخت پرونده',onClick:()=>this.open('ساخت پرونده')},{icon:'fa-solid fa-calendar-plus',label:'رزرو نوبت',onClick:()=>this.open('رزرو نوبت')}];callUser(){this.toast.success('تماس با کاربر برقرار شد')}open(t:string){this.dialog.set(t)}confirmLabel(){return this.dialog()==='ثبت یادداشت'?'ذخیره یادداشت':this.dialog()==='ساخت پرونده'?'ایجاد پرونده':this.dialog()==='رزرو نوبت'?'ثبت نوبت':'ذخیره لید'}save(){this.toast.success(`${this.dialog()} با موفقیت ثبت شد`);this.dialog.set('')}}
