import { Component, signal } from '@angular/core';
import { SidebarComponent } from '../../layout/sidebar/sidebar.component';
import { BaseTableComponent, TableAction } from '../../base/base-table/base-table.component';
import { BaseDialogComponent } from '../../base/base-dialog/base-dialog.component';
import { BaseDatePickerComponent } from '../../base/base-date-picker/base-date-picker.component';
import { leads } from '../../shared/mock-data';
type Attendance='Not Present'|'Present'|'Online'|'Offline'|'Absent';
@Component({selector:'app-consultant', standalone:true, imports:[SidebarComponent, BaseTableComponent, BaseDialogComponent, BaseDatePickerComponent], template:`<div class="dashboard"><app-sidebar title="Consultant" [items]="items"/><section class="panel"><h1>Consultant Dashboard</h1><article class="card attendance"><b>Attendance: {{attendance()}}</b><button class="btn" (click)="attendance.set('Present')">Present</button><button class="btn" [disabled]="attendance()==='Not Present'" (click)="attendance.set('Online')">Online</button><button class="btn" [disabled]="attendance()==='Not Present'" (click)="attendance.set('Offline')">Offline</button><button class="btn danger" [disabled]="attendance()==='Online'" (click)="openAbsent()">Absent</button></article><h2>Leads Management</h2><app-base-table [columns]="cols" [rows]="leads" [customActions]="leadActions" (add)="dialog.set('افزودن لید')"/></section></div><app-base-dialog [open]="!!dialog()" [title]="dialog()" (closed)="dialog.set('')"><div class="form-grid"><textarea class="control" required placeholder="توضیحات / دلیل غیبت"></textarea><input class="control" placeholder="نام پروفایل"/><app-base-date-picker></app-base-date-picker></div></app-base-dialog>`})
export class ConsultantComponent { items=[{label:'Attendance',path:'/consultant'},{label:'Leads',path:'/consultant'}]; attendance=signal<Attendance>('Not Present'); dialog=signal(''); leads=leads; cols=[{key:'name',label:'نام'},{key:'phone',label:'تلفن'},{key:'status',label:'وضعیت'},{key:'description',label:'توضیحات'}]; leadActions:TableAction[]=[{icon:'📞',label:'Call',onClick:()=>this.dialog.set('تماس با لید')},{icon:'📝',label:'Add Description',onClick:()=>this.dialog.set('ثبت توضیح')},{icon:'👤',label:'Create Profile',onClick:()=>this.dialog.set('ساخت پروفایل')},{icon:'📅',label:'Create Reservation',onClick:()=>this.dialog.set('ایجاد رزرو')}]; openAbsent(){this.dialog.set('ثبت دلیل غیبت'); this.attendance.set('Absent');} }
