import { Component, OnDestroy, OnInit, inject, signal } from '@angular/core';
import { NgFor, NgIf } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient, HttpParams } from '@angular/common/http';
import { BaseDialogComponent } from '../../base/base-dialog/base-dialog.component';
import { BaseToastService } from '../../base/base-toast/base-toast.service';

type ApiResult={isSuccess:boolean;message:string};
type PagedResponse<T>={items?:T[];data?:T[];totalCount?:number;pageNumber?:number;pageSize?:number}|T[];
interface LeadAssignmentItem{id:number;userName:string;phoneNumber:string;leadAssignmentState:number;leadAssignmentType:number;}
interface LeadFilters{leadAssignmentState:string;leadAssignmentType:string;pageNumber:number;pageSize:number;tab:string;}
interface ReportForm{leadAssignmentId:number;consultantProfileId:number;callResult:number;reportDescription:string;}
const LeadAssignmentType={RealTime:1,OfflineQueue:2} as const;
function readStorage(key:string,fallback=''){return typeof localStorage==='undefined'?fallback:(localStorage.getItem(key)??fallback);}
function writeStorage(key:string,value:string){if(typeof localStorage!=='undefined')localStorage.setItem(key,value);}
const LeadAssignmentState={Assigned:2,Converted:5,Expired:6,Rejected:7} as const;

@Component({selector:'app-consultant-leads-page',standalone:true,imports:[NgFor,NgIf,FormsModule,BaseDialogComponent],template:`<section class="screen-stack consultant-dashboard">
  <article class="hero-card"><small>داشبورد مشاور</small><h2>لیدهای من</h2><p>مشاهده لیدهای تخصیص‌یافته و ثبت گزارش تماس برای لیدهای لحظه‌ای و صف آفلاین.</p></article>
  <section class="table-card">
    <div class="filter-panel user-filter-grid responsive-filter-panel open">
      <label><span>شناسه پروفایل مشاور</span><input class="control" type="number" [(ngModel)]="profileId" (ngModelChange)="persistProfileId()" /></label>
      <label><span>تب لیدها</span><select class="control" [(ngModel)]="filters.tab" (ngModelChange)="applyTab()"><option value="all">همه لیدها</option><option value="action">نیازمند اقدام</option><option value="offlineOpen">آفلاین باز</option><option value="realTime">RealTime</option><option value="converted">موفق</option><option value="closed">رد/منقضی</option></select></label>
      <label><span>وضعیت</span><select class="control" [(ngModel)]="filters.leadAssignmentState"><option value="">همه</option><option *ngFor="let s of states" [value]="s.value">{{s.label}}</option></select></label>
      <label><span>نوع</span><select class="control" [(ngModel)]="filters.leadAssignmentType"><option value="">همه</option><option [value]="1">لحظه‌ای</option><option [value]="2">آفلاین</option></select></label>
      <button class="btn primary" type="button" (click)="loadLeads()">اعمال فیلترها</button><button class="btn ghost" type="button" (click)="resetFilters()">پاک‌سازی</button>
    </div>
    <div class="state-card">لید آفلاین باز: {{openOfflineCount()}} - لید لحظه‌ای فعال: {{activeRealTimeCount()}}</div>
    <div *ngIf="loading()" class="state-card">در حال دریافت لیدها...</div><div *ngIf="!loading()&&!visibleLeads().length" class="state-card">لیدی برای نمایش وجود ندارد.</div>
    <div class="desktop-table" *ngIf="!loading()&&visibleLeads().length"><table><thead><tr><th>نام مخاطب</th><th>شماره تماس</th><th>نوع لید</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody><tr *ngFor="let lead of visibleLeads()"><td>{{lead.userName}}</td><td>{{lead.phoneNumber}}</td><td>{{leadTypeLabel(lead.leadAssignmentType)}}</td><td>{{leadStateLabel(lead.leadAssignmentState)}}</td><td><button class="icon-btn" type="button" [disabled]="!canReport(lead)" (click)="openReport(lead)"><i class="fa-solid fa-clipboard-check"></i> ثبت گزارش</button></td></tr></tbody></table></div>
    <div class="mobile-cards" *ngIf="!loading()&&visibleLeads().length"><article class="mobile-row-card" *ngFor="let lead of visibleLeads()"><dl><dt>نام</dt><dd>{{lead.userName}}</dd><dt>شماره</dt><dd>{{lead.phoneNumber}}</dd><dt>نوع</dt><dd>{{leadTypeLabel(lead.leadAssignmentType)}}</dd><dt>وضعیت</dt><dd>{{leadStateLabel(lead.leadAssignmentState)}}</dd></dl><button class="btn ghost" type="button" [disabled]="!canReport(lead)" (click)="openReport(lead)">ثبت گزارش</button></article></div>
    <footer class="pagination"><button class="btn ghost" [disabled]="filters.pageNumber===1" (click)="changePage(filters.pageNumber-1)">قبلی</button><label class="page-size-control"><span>تعداد</span><select class="control" [ngModel]="filters.pageSize" (ngModelChange)="setPageSize($event)"><option [ngValue]="5">5</option><option [ngValue]="10">10</option><option [ngValue]="20">20</option></select></label><span>صفحه {{filters.pageNumber}} از {{totalPages()}} - کل: {{totalCount()}}</span><button class="btn ghost" [disabled]="filters.pageNumber===totalPages()" (click)="changePage(filters.pageNumber+1)">بعدی</button></footer>
  </section>
</section><app-base-dialog [open]="reportOpen()" title="ثبت گزارش تماس لید" confirmLabel="ثبت گزارش" (closed)="reportOpen.set(false)" (confirm)="submitReport()"><div class="form-grid"><select class="control" [(ngModel)]="reportForm.callResult"><option *ngFor="let r of callResults" [ngValue]="r.value">{{r.label}}</option></select><textarea class="control" [(ngModel)]="reportForm.reportDescription" placeholder="توضیحات تماس"></textarea></div></app-base-dialog>`})
export class ConsultantLeadsPage implements OnInit,OnDestroy{private readonly http=inject(HttpClient);private readonly toast=inject(BaseToastService);private readonly apiBase='http://localhost:5182/api';private poll?:ReturnType<typeof setInterval>;
profileId=Number(readStorage('consultantProfileId','0'));readonly leads=signal<LeadAssignmentItem[]>([]);readonly loading=signal(false);readonly totalCount=signal(0);readonly totalPages=signal(1);readonly reportOpen=signal(false);filters:LeadFilters={leadAssignmentState:'',leadAssignmentType:'',pageNumber:1,pageSize:10,tab:'all'};reportForm:ReportForm={leadAssignmentId:0,consultantProfileId:this.profileId,callResult:1,reportDescription:''};
states=[{value:1,label:'جدید'},{value:2,label:'تخصیص‌یافته'},{value:3,label:'تماس/پیگیری'},{value:4,label:'در انتظار'},{value:5,label:'تبدیل‌شده'},{value:6,label:'منقضی'},{value:7,label:'رد شده'}];callResults=[{value:1,label:'تماس برقرار شد'},{value:2,label:'تبدیل شد'},{value:3,label:'رد شد'},{value:4,label:'پاسخ نداد'},{value:5,label:'شماره اشتباه'},{value:6,label:'نیاز به پیگیری'}];
ngOnInit(){this.loadLeads();this.poll=setInterval(()=>{if(!this.reportOpen())this.loadLeads(false);},60000);}ngOnDestroy(){if(this.poll)clearInterval(this.poll);}persistProfileId(){writeStorage('consultantProfileId',String(this.profileId||''));this.reportForm.consultantProfileId=this.profileId;this.loadLeads();}
visibleLeads(){const rows=this.leads();switch(this.filters.tab){case'action':return rows.filter(l=>l.leadAssignmentState===LeadAssignmentState.Assigned);case'offlineOpen':return rows.filter(l=>l.leadAssignmentType===LeadAssignmentType.OfflineQueue&&!this.isFinal(l.leadAssignmentState));case'realTime':return rows.filter(l=>l.leadAssignmentType===LeadAssignmentType.RealTime);case'converted':return rows.filter(l=>l.leadAssignmentState===LeadAssignmentState.Converted);case'closed':return rows.filter(l=>[LeadAssignmentState.Rejected,LeadAssignmentState.Expired].includes(l.leadAssignmentState as 6|7));default:return rows;}}
openOfflineCount(){return this.leads().filter(l=>l.leadAssignmentType===LeadAssignmentType.OfflineQueue&&!this.isFinal(l.leadAssignmentState)).length;}activeRealTimeCount(){return this.leads().filter(l=>l.leadAssignmentType===LeadAssignmentType.RealTime&&l.leadAssignmentState===LeadAssignmentState.Assigned).length;}
applyTab(){this.filters.pageNumber=1;this.loadLeads();}resetFilters(){this.filters={leadAssignmentState:'',leadAssignmentType:'',pageNumber:1,pageSize:10,tab:'all'};this.loadLeads();}changePage(p:number){this.filters.pageNumber=p;this.loadLeads();}setPageSize(s:number){this.filters.pageSize=Number(s);this.filters.pageNumber=1;this.loadLeads();}
loadLeads(showError=true){if(!this.profileId)return;this.loading.set(true);this.http.get<PagedResponse<LeadAssignmentItem>>(`${this.apiBase}/Consultant/GetLeads`,{params:this.params()}).subscribe({next:r=>{const items=Array.isArray(r)?r:(r.items??r.data??[]);const total=Array.isArray(r)?r.length:(r.totalCount??items.length);this.leads.set(items);this.totalCount.set(total);this.totalPages.set(Math.max(1,Math.ceil(total/this.filters.pageSize)));this.loading.set(false);},error:()=>{if(showError)this.toast.error('دریافت لیدها ناموفق بود');this.loading.set(false);}});}
canReport(l:LeadAssignmentItem){return l.leadAssignmentState===LeadAssignmentState.Assigned;}openReport(l:LeadAssignmentItem){this.reportForm={leadAssignmentId:l.id,consultantProfileId:this.profileId,callResult:1,reportDescription:''};this.reportOpen.set(true);}submitReport(){this.http.post<ApiResult>(`${this.apiBase}/Consultant/SubmitLeadCallReport`,this.reportForm).subscribe({next:r=>{r.isSuccess?this.toast.success(r.message):this.toast.error(r.message);if(r.isSuccess){writeStorage('consultantIsOnline',String(r.message.includes('خودکار آنلاین شدید')));this.reportOpen.set(false);this.loadLeads(false);}},error:()=>this.toast.error('ثبت گزارش تماس ناموفق بود')});}
leadStateLabel(v:number){return this.states.find(s=>s.value===v)?.label??'نامشخص';}leadTypeLabel(v:number){return v===1?'لحظه‌ای':v===2?'آفلاین':'نامشخص';}private isFinal(s:number){return [LeadAssignmentState.Converted,LeadAssignmentState.Rejected,LeadAssignmentState.Expired].includes(s as 5|6|7);}private params(){let p=new HttpParams().set('profileId',this.profileId).set('pageNumber',this.filters.pageNumber).set('pageSize',this.filters.pageSize);if(this.filters.leadAssignmentState)p=p.set('leadAssignmentState',this.filters.leadAssignmentState);if(this.filters.leadAssignmentType)p=p.set('leadAssignmentType',this.filters.leadAssignmentType);return p;}}
