import { Component, inject, signal } from '@angular/core';
import { BaseTableComponent, TableAction } from '../../base/base-table/base-table.component';
import { BaseDialogComponent } from '../../base/base-dialog/base-dialog.component';
import { BaseDatePickerComponent } from '../../base/base-date-picker/base-date-picker.component';
import { BaseToastService } from '../../base/base-toast/base-toast.service';
import { leads, profiles, reservations } from '../../shared/mock-data';
type Attendance='Not Present'|'Present'|'Online'|'Offline'|'Absent';

@Component({selector:'app-consultant', standalone:true, imports:[BaseTableComponent, BaseDialogComponent, BaseDatePickerComponent], template:`
  <section class="screen-stack"><article class="hero-card"><small>Consultant</small><h2>وضعیت حضور: {{attendance()}}</h2><p>State machine نمایشی برای کنترل حضور مشاور.</p></article>
  <div class="quick-actions"><button class="btn primary" [disabled]="attendance()==='Online' || attendance()==='Present'" (click)="setAttendance('Present')">Mark Present</button><button class="btn" [disabled]="attendance()==='Not Present' || attendance()==='Absent'" (click)="setAttendance('Online')">Online</button><button class="btn" [disabled]="attendance()==='Not Present' || attendance()==='Absent'" (click)="setAttendance('Offline')">Offline</button><button class="btn danger" [disabled]="attendance()==='Online' || attendance()==='Not Present' || attendance()==='Absent'" (click)="dialog.set('دلیل غیبت')">Absent</button></div>
  <app-base-table [columns]="leadCols" [rows]="leads" [filters]="leadFilters" [customActions]="leadActions" (add)="open('افزودن لید')" />
  <app-base-table [columns]="profileCols" [rows]="profiles" [filters]="profileFilters" (add)="open('ساخت پروفایل')" />
  <app-base-table [columns]="reservationCols" [rows]="reservations" [filters]="reservationFilters" (add)="open('ایجاد رزرو')" /></section>
  <app-base-dialog [open]="!!dialog()" [title]="dialog()" (closed)="dialog.set('')" (confirm)="confirmDialog()"><div class="form-grid"><textarea class="control" required placeholder="توضیحات / دلیل غیبت اجباری"></textarea><input class="control" placeholder="نام بیمار یا لید"/><app-base-date-picker /></div></app-base-dialog>`})
export class ConsultantComponent { private toast=inject(BaseToastService); attendance=signal<Attendance>('Not Present'); dialog=signal(''); leads=leads; profiles=profiles; reservations=reservations; leadCols=[{key:'name',label:'نام'},{key:'phone',label:'تلفن'},{key:'status',label:'وضعیت'},{key:'description',label:'توضیحات'}]; profileCols=[{key:'name',label:'نام'},{key:'phone',label:'تلفن'},{key:'treatment',label:'درمان'}]; reservationCols=[{key:'date',label:'تاریخ'},{key:'time',label:'ساعت'},{key:'consultant',label:'مشاور'},{key:'status',label:'وضعیت'}]; leadFilters=[{key:'status',label:'وضعیت',type:'select' as const,options:['New','Called']},{key:'description',label:'درمان',type:'text' as const}]; profileFilters=[{key:'treatment',label:'درمان',type:'text' as const}]; reservationFilters=[{key:'status',label:'وضعیت',type:'select' as const,options:['Confirmed','Pending']}]; leadActions:TableAction[]=[{icon:'☎️',label:'Call user',onClick:()=>this.open('تماس با لید')},{icon:'📝',label:'Add note',onClick:()=>this.open('ثبت توضیح')},{icon:'👤',label:'Create profile',onClick:()=>this.open('ساخت پروفایل')},{icon:'📅',label:'Reserve appointment',onClick:()=>this.open('ایجاد رزرو')}]; setAttendance(state:Attendance){this.attendance.set(state); this.toast.success('وضعیت حضور به‌روزرسانی شد')} open(title:string){this.dialog.set(title)} confirmDialog(){if(this.dialog()==='دلیل غیبت'){this.attendance.set('Absent')} this.toast.success('عملیات نمایشی ثبت شد'); this.dialog.set('')} }
