import { Component, inject, signal } from '@angular/core';
import { Router } from '@angular/router';
import { BaseTableComponent, TableAction } from '../../base/base-table/base-table.component';
import { BaseDialogComponent } from '../../base/base-dialog/base-dialog.component';
import { BaseDatePickerComponent } from '../../base/base-date-picker/base-date-picker.component';
import { BaseToastService } from '../../base/base-toast/base-toast.service';
import { leads, profiles, reservations } from '../../shared/mock-data';
type Attendance='ثبت‌نشده'|'حاضر'|'آنلاین'|'آفلاین'|'غایب';

@Component({selector:'app-consultant', standalone:true, imports:[BaseTableComponent, BaseDialogComponent, BaseDatePickerComponent], template:`
  <section class="screen-stack consultant-dashboard"><article class="hero-card"><small>داشبورد مشاور</small><h2>{{ pageTitle() }}</h2><p>{{ pageDescription() }}</p></article>
  @if (section() === 'dashboard') {
    <article class="state-card"><h3>وضعیت حضور: {{attendance()}}</h3><p>مشاور ابتدا حضور را ثبت می‌کند، سپس آنلاین/آفلاین می‌شود یا با ثبت دلیل غیبت می‌زند.</p><div class="quick-actions"><button class="btn primary" [disabled]="attendance()==='آنلاین' || attendance()==='حاضر'" (click)="setAttendance('حاضر')">ثبت حضور</button><button class="btn" [disabled]="attendance()==='ثبت‌نشده' || attendance()==='غایب'" (click)="setAttendance('آنلاین')">آنلاین</button><button class="btn" [disabled]="attendance()==='ثبت‌نشده' || attendance()==='غایب'" (click)="setAttendance('آفلاین')">آفلاین</button><button class="btn danger" [disabled]="attendance()==='آنلاین' || attendance()==='ثبت‌نشده' || attendance()==='غایب'" (click)="dialog.set('دلیل غیبت')">غایب</button></div></article>
  } @else if (section() === 'leads') {
    <app-base-table [columns]="leadCols" [rows]="leads" [filters]="leadFilters" [customActions]="leadActions" (add)="open('افزودن لید')" />
  } @else if (section() === 'profiles') {
    <app-base-table [columns]="profileCols" [rows]="profiles" [filters]="profileFilters" (add)="open('ساخت پروفایل')" />
  } @else {
    <app-base-table [columns]="reservationCols" [rows]="reservations" [filters]="reservationFilters" (add)="open('ایجاد رزرو')" />
  }</section>
  <app-base-dialog [open]="!!dialog()" [title]="dialog()" (closed)="dialog.set('')" (confirm)="confirmDialog()"><div class="form-grid"><textarea class="control" required placeholder="توضیحات / دلیل غیبت اجباری"></textarea><input class="control" placeholder="نام بیمار یا لید"/><app-base-date-picker /></div></app-base-dialog>`})
export class ConsultantComponent { private toast=inject(BaseToastService); private router=inject(Router); attendance=signal<Attendance>('ثبت‌نشده'); dialog=signal(''); leads=leads; profiles=profiles; reservations=reservations; leadCols=[{key:'name',label:'نام'},{key:'phone',label:'تلفن'},{key:'status',label:'وضعیت'},{key:'description',label:'توضیحات'}]; profileCols=[{key:'name',label:'نام'},{key:'phone',label:'تلفن'},{key:'treatment',label:'درمان'}]; reservationCols=[{key:'date',label:'تاریخ'},{key:'time',label:'ساعت'},{key:'consultant',label:'مشاور'},{key:'status',label:'وضعیت'}]; leadFilters=[{key:'status',label:'وضعیت',type:'select' as const,options:['جدید','تماس گرفته']},{key:'description',label:'درمان',type:'text' as const}]; profileFilters=[{key:'treatment',label:'درمان',type:'text' as const}]; reservationFilters=[{key:'status',label:'وضعیت',type:'select' as const,options:['تاییدشده','در انتظار']}]; leadActions:TableAction[]=[{icon:'☎️',label:'تماس با کاربر',onClick:()=>this.open('تماس با لید')},{icon:'📝',label:'ثبت یادداشت',onClick:()=>this.open('ثبت توضیح')},{icon:'👤',label:'ساخت پرونده',onClick:()=>this.open('ساخت پروفایل')},{icon:'📅',label:'رزرو نوبت',onClick:()=>this.open('ایجاد رزرو')}]; section(){return this.router.url.includes('/leads')?'leads':this.router.url.includes('/profiles')?'profiles':this.router.url.includes('/reservations')?'reservations':'dashboard'} pageTitle(){return this.section()==='dashboard'?'کنترل حضور مشاور':this.section()==='leads'?'لیدهای من':this.section()==='profiles'?'پرونده‌های بیمار':'رزروهای مشاور'} pageDescription(){return this.section()==='dashboard'?'ثبت حضور، آنلاین/آفلاین و غیبت.':this.section()==='leads'?'تماس، یادداشت، ساخت پرونده و رزرو برای لیدها.':this.section()==='profiles'?'مشاهده و ساخت پروفایل بیماران.':'ایجاد و پیگیری نوبت‌های رزرو شده.'} setAttendance(state:Attendance){this.attendance.set(state); this.toast.success('وضعیت حضور به‌روزرسانی شد')} open(title:string){this.dialog.set(title)} confirmDialog(){if(this.dialog()==='دلیل غیبت'){this.attendance.set('غایب')} this.toast.success('عملیات نمایشی ثبت شد'); this.dialog.set('')} }
